### ISSUE TITLE
Provide option to generate selectors/mixins with image's width and height

### ISSUE THREAD

**Issue by eshiota** [lucasmazza/spriteful#16]
When generating a CSS/SCSS file, there could be an option to include the single image's dimensions. Something like:

`spriteful icons -f scss --dimensions`

``` scss
%icons-sprite-myicon {
  @extend %icons-sprite;
  background-position: 0px 0px;
  width: 10px;
  height: 10px;
}
```

Or maybe, a separate placeholder selector/mixin:

``` scss
%icons-sprite-myicon-dimensioned {
  @extend %icons-sprite-myicon;
  width: 10px;
  height: 10px;
}
```
